- name: disable some services
  service:
    name: "{{ item }}"
    state: stopped
    enabled: False
  with_items:
  - firewalld
  - NetworkManager

- name: disable selinux
  selinux:
    state: disabled
  notify: reboot

- name: reboot
  meta: flush_handlers

- block:
  - name: backup repo
    copy:
      src: "/etc/yum.repos.d"
      remote_src: yes
      dest: "/etc/yum_bak"
      force: no

  - name: remove old repo
    file:
      path: "/etc/yum.repos.d"
      state: absent

  - name: copy repo
    copy:
      src: "repo/{{ansible_distribution | lower}}-{{ansible_distribution_major_version}}/yum.repos.d"
      dest: "/etc/"
      force: yes

  - name: flush yum repo
    yum:
      update_cache: yes
  ignore_errors: True
