- block:
  - name: download filebeat binaries
    unarchive:
      src: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-{{ log.elastic.version }}-linux-{{ ansible_architecture }}.tar.gz
      dest: /tmp/
      remote_src: yes
  - name: copy filebeat binaries
    copy:
      src: /tmp/filebeat-{{ log.elastic.version }}-linux-{{ ansible_architecture }}/filebeat
      dest: "{{ log.elastic.filebeat.install_path }}"
      mode: 0755
      remote_src: yes
  when: log.elastic.filebeat.local_dir.strip() == ""

- name: copy filebeat binaries
  copy:
    src: "{{ log.elastic.filebeat.local_dir }}"
    dest: "{{ log.elastic.filebeat.install_path }}"
    mode: 0755
  when: log.elastic.filebeat.local_dir.strip() != ""

- name: mkdir /etc/filebeat
  file:
    path: "/etc/filebeat"
    state: directory
    mode: 0664

- name: copy filebeat config file
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml

- name: Get systemd version
  command: systemctl --version
  changed_when: false
  check_mode: false
  register: __systemd_version
  tags:
    - skip_ansible_lint

- name: Set systemd version fact
  set_fact:
    filebeat_systemd_version: "{{ __systemd_version.stdout_lines[0] | regex_replace('^systemd\\s(\\d+).*$', '\\1') }}"

- name: copy systemd file
  template:
    src: filebeat.service.j2
    dest: /etc/systemd/system/filebeat.service
  notify: restart filebeat

- name: systemd reload
  systemd:
    daemon_reload: True

- name: flush handlers
  meta: flush_handlers
