- name: set fact
  set_fact:
    __path: ""

- name: set proxy fact
  set_fact:
    __proxy_env:
      HTTP_PROXY: "{{ chart.http_proxy.server }}"
      HTTPS_PROXY: "{{ chart.http_proxy.server }}"
      NO_PROXY: "{{ chart.http_proxy.no_proxy }}"
  when: chart.http_proxy.enabled == True

- block:
  - name: copy charts
    copy:
      src: "{{ chart.local_dir.rstrip('/') }}/"
      dest: "/tmp/"
      force: true
  - name: set fact
    set_fact:
      __path: "/tmp/"
  when: chart.local_dir.strip() != ""

- name: setup cert-manager
  include_tasks: setup.yaml

- name: copy files
  copy:
    src: "{{ item }}"
    dest: /tmp/
  with_items:
  - "secrets.yaml"
  - "issuer.yaml"

- name: apply secret
  shell: "kubectl apply -f /tmp/secrets.yaml -n {{ basic.namespace }}"

- name: apply issuer
  shell: "kubectl apply -f /tmp/issuer.yaml"
