- hosts: ansible
  gather_facts: True
  become: True
  tasks:
  - name: disable selinux
    selinux:
      state: disabled
    notify: reboot host
  - name: include docker role
    include_role:
      name: docker
  handlers:
  - name: reboot host
    reboot:
