- name: install kafka
  kubernetes.core.helm:
    chart_ref: "{{ __path }}{{ service.kafka.chart.path }}"
    chart_repo_url: "{{ chart.repo['bitnami'] }}"
    chart_version: "{{ service.kafka.chart.version }}"
    release_name: "{{ service.kafka.name }}"
    release_namespace: "{{ service.namespace }}"
    create_namespace: yes
    atomic: yes
    release_values:
      zookeeper:
        image:
          registry: "{{ service.repository.strip('/') }}"
        persistence:
          storageClass: "{{ service.storage_class }}"
        jvmFlags: "{{ service.kafka.resources.zookeeper.jvmFlags }}"
        resources:
          limits: "{{ service.kafka.resources.zookeeper.limits }}"
          requests: "{{ service.kafka.resources.zookeeper.requests }}"
      image:
        registry: "{{ service.repository.strip('/') }}"
      replicaCount: "{{ service.kafka.replicas }}"
      numPartitions: "{{ service.kafka.replicas }}"
      externalAccess:
        enabled: true
        service:
          type: NodePort
          domain: "{{ __domain }}"
          nodePorts: "{{ service.kafka.node_ports }}"
      persistence:
        storageClass: "{{ service.storage_class }}"
      heapOpts: "{{ service.kafka.resources.heapOpts }}"
      resources:
        limits: "{{ service.kafka.resources.limits }}"
        requests: "{{ service.kafka.resources.requests }}"
