- name: download operator yaml
  get_url:
    url: "https://github.com/jaegertracing/jaeger-operator/releases/download/v{{ service_mesh.jaeger.version }}/jaeger-operator.yaml"
    dest: /tmp/jaeger-operator.yaml
    environment: "{{ __proxy_env | default(omit) }}"
  when: service_mesh.jaeger.local_path.strip() == ""

- name: copy jaeger operator yaml
  copy:
    src: "{{ service_mesh.jaeger.local_path }}"
    dest: /tmp/jaeger-operator.yaml
  when: service_mesh.jaeger.local_path.strip() != ""

- name: get image
  #must escape \ in ansible
  shell: |
    sed -n -E  's@image: (\S*)@image: {{ service_mesh.repository }}\1@g;/image: (\S*)/p' /tmp/jaeger-operator.yaml
  register: jaeger_template_result

- name: set facts
  set_fact:
    jaeger_template_stdout: "{{ jaeger_template_result.stdout_lines }}"

- name: get images
  set_fact:
    jaeger_images: "{{ (jaeger_template_stdout | select('match', '.*image:.*') | list + [service_mesh.repository+'jaegertracing/jaeger-collector:'+service_mesh.jaeger.version,service_mesh.repository+'jaegertracing/jaeger-query:'+service_mesh.jaeger.version,service_mesh.repository+'jaegertracing/jaeger-agent:'+service_mesh.jaeger.version]) | regex_replace(' *image: *', '') | replace('\"', '') }}"
