- block:
  - name: download node exporter binaries
    unarchive:
      src: https://github.com/prometheus/node_exporter/releases/download/v{{ monitor.node_exporter.version }}/node_exporter-{{ monitor.node_exporter.version }}.linux-{{ go_arch }}.tar.gz
      dest: /tmp/
      remote_src: yes
  - name: copy node exporter binaries
    copy:
      src: /tmp/node_exporter-{{ monitor.node_exporter.version }}.linux-{{ go_arch }}/node_exporter
      dest: "{{ monitor.node_exporter.install_path }}"
      mode: 0755
      remote_src: yes
  when: monitor.node_exporter.local_path.strip() == ""

- name: copy node exporter binaries
  copy:
    src: "{{ monitor.node_exporter.local_path }}"
    dest: "{{ monitor.node_exporter.install_path }}"
    mode: 0755
  when: monitor.node_exporter.local_path.strip() != ""

- name: Get systemd version
  command: systemctl --version
  changed_when: false
  check_mode: false
  register: __systemd_version
  tags:
    - skip_ansible_lint

- name: Set systemd version fact
  set_fact:
    node_exporter_systemd_version: "{{ __systemd_version.stdout_lines[0] | regex_replace('^systemd\\s(\\d+).*$', '\\1') }}"

- name: copy systemd file
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
  notify: restart node_exporter

- name: systemd reload
  systemd:
    daemon_reload: True

- name: flush handlers
  meta: flush_handlers
